version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  serial-metrics:

services:


  prometheus:
    image: prom/prometheus:v2.19.0
    container_name: monitoring_prometheus
    volumes:
      - ./data/prometheus/:/etc/prometheus/
      - prometheus_data:/data/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      - serial-metrics
    restart: always



  grafana:
    image: grafana/grafana:7.0.3
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./data/grafana/config.monitoring
    networks:
      - serial-metrics
    restart: always